### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by caipng** [AY2122S1-CS2103-W14-3/tp#32]
- [ ] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/28
- [ ] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/31
- [ ] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/29
- [ ] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/30
