### ISSUE TITLE
Modules & Classes

### ISSUE THREAD

**Issue by caipng** [AY2122S1-CS2103-W14-3/tp#37]
**Module**: A NUS module. It consists of Module coordinators, TAs and students.

**Class**: Collection of students taught by a TA. One class is associated with one module, and a venue and time.

## Progress

Module CRUD

- [x] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/22
- [x] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/33

Classes CRUD

- [x] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/25
- [x] https://github.com/AY2122S1-CS2103-W14-3/tp/issues/36
